# Generated by Django 3.1.6 on 2021-02-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_auto_20210211_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforcedetails',
            name='email_bounced',
            field=models.CharField(choices=[('none', 'None'), ('Open-Not Contacted', 'Open-Not Contacted'), ('Working-Contacted', 'Working-Contacted'), ('Closed-Converted', 'Closed-Converted'), ('Closed-Not Converted', 'Closed-Not Converted')], default='none', max_length=90),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='lead_ignored',
            field=models.CharField(choices=[('none', 'None'), ('Open-Not Contacted', 'Open-Not Contacted'), ('Working-Contacted', 'Working-Contacted'), ('Closed-Converted', 'Closed-Converted'), ('Closed-Not Converted', 'Closed-Not Converted')], default='none', max_length=90),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='lead_lost',
            field=models.CharField(choices=[('none', 'None'), ('Open-Not Contacted', 'Open-Not Contacted'), ('Working-Contacted', 'Working-Contacted'), ('Closed-Converted', 'Closed-Converted'), ('Closed-Not Converted', 'Closed-Not Converted')], default='none', max_length=90),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='lead_opened',
            field=models.CharField(choices=[('none', 'None'), ('Open-Not Contacted', 'Open-Not Contacted'), ('Working-Contacted', 'Working-Contacted'), ('Closed-Converted', 'Closed-Converted'), ('Closed-Not Converted', 'Closed-Not Converted')], default='none', max_length=90),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='lead_resubscribed',
            field=models.CharField(choices=[('none', 'None'), ('Open-Not Contacted', 'Open-Not Contacted'), ('Working-Contacted', 'Working-Contacted'), ('Closed-Converted', 'Closed-Converted'), ('Closed-Not Converted', 'Closed-Not Converted')], default='none', max_length=90),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='lead_unsubcribed',
            field=models.CharField(choices=[('none', 'None'), ('Open-Not Contacted', 'Open-Not Contacted'), ('Working-Contacted', 'Working-Contacted'), ('Closed-Converted', 'Closed-Converted'), ('Closed-Not Converted', 'Closed-Not Converted')], default='none', max_length=90),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='lead_won',
            field=models.CharField(choices=[('none', 'None'), ('Open-Not Contacted', 'Open-Not Contacted'), ('Working-Contacted', 'Working-Contacted'), ('Closed-Converted', 'Closed-Converted'), ('Closed-Not Converted', 'Closed-Not Converted')], default='none', max_length=90),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='missing',
            field=models.CharField(choices=[('Create them', 'Create them'), ('Do nothing', 'Do nothing')], default='Contacts', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='object_type_people',
            field=models.CharField(choices=[('Leads', 'Lead'), ('Contacts', 'Contact')], default='Contacts', max_length=12),
        ),
        migrations.AlterField(
            model_name='salesforcedetails',
            name='track_event',
            field=models.CharField(choices=[('All Mailsaas Prospects', 'All Mailsaas Prospects'), ('Only Mailsaas Leads', 'Only Mailsaas Leads')], default='Contacts', max_length=50),
        ),
    ]
