# Generated by Django 3.1.6 on 2021-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_auto_20210211_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforcedetails',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
