# Generated by Django 3.1.4 on 2021-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Account')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
