<<<<<<< HEAD
# Generated by Django 3.1.4 on 2021-02-09 07:41
=======
# Generated by Django 3.1.6 on 2021-02-09 12:49
>>>>>>> a9f5fb7059a16c9558afa0e21a18ea961f1c117c

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unsubscribes', '0001_initial'),
=======
        ('unsubscribes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> a9f5fb7059a16c9558afa0e21a18ea961f1c117c
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribeemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
