# Generated by Django 3.1.4 on 2021-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsubscribes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubcribeCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unscribe_emails', models.FileField(blank=True, null=True, upload_to='unsubcribe_csv_uploads/')),
            ],
        ),
    ]
