# Generated by Django 3.1.4 on 2021-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsubscribes', '0002_unsubcribecsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribeemail',
            name='mail_account',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
