# Generated by Django 3.1.6 on 2021-02-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsubscribes', '0002_unsubscribeemail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribeemail',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
