# Generated by Django 3.1.6 on 2021-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsubscribes', '0003_auto_20210211_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribeemail',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
