# Generated by Django 3.1.4 on 2021-02-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsubscribes', '0004_unsubscribeemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribeemail',
            name='on_delete',
            field=models.BooleanField(default=False),
        ),
    ]
