# Generated by Django 3.1.4 on 2021-03-26 05:51

import apps.users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, storage=apps.users.storage.OverwriteStorage(), upload_to='profile-pictures/'),
        ),
    ]
