# Generated by Django 3.1.4 on 2021-04-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210326_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
