# Generated by Django 3.1.4 on 2021-01-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_mailsaas_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mailsaas_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.mailsaastype'),
            preserve_default=False,
        ),
    ]
