# Generated by Django 3.1.4 on 2021-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mail_account',
            field=models.EmailField(max_length=254, verbose_name='Mail Account'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='max_email',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='max_email_send',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='min_email_send',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mint_between_sends',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
