# Generated by Django 3.1.4 on 2021-02-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailaccounts', '0001_initial'),
        ('campaignschedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='mail_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailaccounts.emailaccount'),
        ),
    ]
