# Generated by Django 3.1.4 on 2021-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_schedule',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
