# Generated by Django 3.1.4 on 2021-02-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0001_initial'),
        ('campaignschedule', '0002_auto_20210211_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='mail_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailaccounts.emailaccount'),
        ),
    ]
