# Generated by Django 3.1.4 on 2021-02-02 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0002_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
