# Generated by Django 3.1.4 on 2021-02-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0003_auto_20210211_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='min_email_send',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
