# Generated by Django 3.1.4 on 2021-03-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0003_auto_20210306_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='strategy',
        ),
    ]
