# Generated by Django 3.1.4 on 2021-02-02 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0004_auto_20210202_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_account', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mail Account')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(blank=True, null=True)),
                ('recipient', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('email_body', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='mint_email_send',
            new_name='min_email_send',
        ),
    ]
