# Generated by Django 3.1.4 on 2021-02-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0005_auto_20210202_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
