# Generated by Django 3.1.4 on 2021-02-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0007_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='strategy',
            field=models.CharField(choices=[('SPACE', 'Space out over the day'), ('SEND', 'Send as fast as possible')], max_length=20),
        ),
    ]
