# Generated by Django 3.1.4 on 2021-02-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0008_auto_20210203_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='next_email_send_at_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
