# Generated by Django 3.1.4 on 2021-02-03 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0011_auto_20210203_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='block_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default=['sunday'], size=None),
        ),
    ]
