# Generated by Django 3.1.4 on 2021-02-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0014_auto_20210203_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='block_days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='block_days',
            field=models.ManyToManyField(to='campaignschedule.WeekDays'),
        ),
    ]
