# Generated by Django 3.1.4 on 2021-02-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaignschedule', '0015_auto_20210203_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='next_email_send_at_time',
        ),
    ]
