# Generated by Django 3.1.4 on 2021-02-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaignschedule', '0016_remove_schedule_next_email_send_at_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_schedule',
            old_name='recipient',
            new_name='recipient_email',
        ),
        migrations.AddField(
            model_name='email_schedule',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email_schedule',
            name='mail_account',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
