# Generated by Django 3.1.4 on 2021-01-25 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fromAddress', models.CharField(max_length=200)),
                ('csvFile_op1', models.FileField(blank=True, null=True, upload_to='csv_uploads/')),
                ('created_date_time', models.DateTimeField(auto_now=True)),
                ('trackOpens', models.BooleanField(default=False)),
                ('trackLinkClick', models.BooleanField(default=False)),
                ('scheduleThisSend', models.BooleanField(default=False)),
                ('termsAndLaws', models.BooleanField(default=False)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='On_Link_Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitDays', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=2000)),
                ('emailBody', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Follow_up_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitDays', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=2000)),
                ('emailBody', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Drip_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitDays', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=2000)),
                ('emailBody', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=2000, null=True)),
                ('emailBody', models.TextField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('leads', models.BooleanField(default=False)),
                ('replies', models.BooleanField(default=False)),
                ('opens', models.BooleanField(default=False)),
                ('bounces', models.BooleanField(default=False)),
                ('leadStatus', models.CharField(blank=True, choices=[('none', 'none'), ('openLead', 'openLead'), ('wonLead', 'wonLead'), ('lostLead', 'lostLead'), ('ignoredLead', 'ignoredLead')], default='none', max_length=32, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
