# Generated by Django 3.1.4 on 2021-01-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduleDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
