# Generated by Django 3.1.4 on 2021-02-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignrecipient',
            old_name='created_date',
            new_name='created_date_time',
        ),
    ]
