# Generated by Django 3.1.4 on 2021-01-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_email',
            name='has_link_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
