# Generated by Django 3.1.4 on 2021-01-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduleDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduleTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
