# Generated by Django 3.1.4 on 2021-03-18 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0006_sendingcalendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('csv_fields', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=True)),
                ('created_at', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='label_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='campaign.campaignlabel'),
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email_subject', models.CharField(blank=True, max_length=2000, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('has_follow_up', models.BooleanField(default=False)),
                ('has_drips', models.BooleanField(default=False)),
                ('terms_and_laws', models.BooleanField(default=False)),
                ('campaign_status', models.BooleanField(default=False)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('csvfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.uploadfiles')),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailaccounts.emailaccount')),
                ('label_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaignlabel')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('replacement', models.TextField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_reply', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('is_bounce', models.BooleanField(default=False)),
                ('engaged', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField()),
                ('lead_type', models.CharField(choices=[('none', 'None'), ('openLead', 'Open Lead'), ('wonLead', 'Won Lead'), ('lostLead', 'Lost Lead'), ('ignoredLead', 'Ignored Lead'), ('forwardedLead', 'Forwarded Lead')], default='none', max_length=32, null=True)),
                ('created_at', models.TimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.TimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
