# Generated by Django 3.1.4 on 2021-02-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignleadcatcher',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
