# Generated by Django 3.1.4 on 2021-02-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20210203_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='csvfile_op1',
            field=models.FileField(blank=True, null=True, upload_to='camp_csv_uploads/'),
        ),
    ]
