# Generated by Django 3.1.4 on 2021-01-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_email_has_link_clicked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaign_email',
            new_name='CampaignRecipient',
        ),
    ]
