# Generated by Django 3.1.4 on 2021-01-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='bounces',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='opens',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sent',
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='bounces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='opens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='replies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
