# Generated by Django 3.1.4 on 2021-01-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_scheduledatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='termsAndLows',
            new_name='termsAndLaws',
        ),
    ]
