# Generated by Django 3.1.4 on 2021-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20210125_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
