# Generated by Django 3.1.4 on 2021-01-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20210128_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='unsubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
