# Generated by Django 3.1.4 on 2021-02-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaignleadcatcher_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignleadcatcher',
            name='is_delete',
        ),
    ]
