# Generated by Django 3.1.4 on 2021-03-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0006_sendingcalendar'),
        ('campaign', '0003_auto_20210319_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='track_opens',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='from_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailaccounts.emailaccount'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='label_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='campaign.campaignlabel'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='terms_and_laws',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CampaignLabels',
        ),
    ]
