# Generated by Django 3.1.4 on 2021-01-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20210128_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow_up_email',
            new_name='DripEmailModel',
        ),
        migrations.RenameModel(
            old_name='On_Link_Click',
            new_name='EmailOnLinkClick',
        ),
        migrations.RenameModel(
            old_name='Drip_email',
            new_name='FollowUpEmail',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='csvFile_op1',
            new_name='csvfile_op1',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='fromAddress',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='scheduleDate',
            new_name='schedule_date',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='scheduleThisSend',
            new_name='schedule_send',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='scheduleTime',
            new_name='schedule_time',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='termsAndLaws',
            new_name='terms_and_laws',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='trackLinkClick',
            new_name='track_linkclick',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='trackOpens',
            new_name='track_opens',
        ),
        migrations.RenameField(
            model_name='campaignleadcatcher',
            old_name='leadCatcherRecipient',
            new_name='leadcatcher_recipient',
        ),
        migrations.RenameField(
            model_name='campaignrecipient',
            old_name='emailBody',
            new_name='email_body',
        ),
        migrations.RenameField(
            model_name='campaignrecipient',
            old_name='leadStatus',
            new_name='lead_status',
        ),
        migrations.RenameField(
            model_name='dripemailmodel',
            old_name='emailBody',
            new_name='email_body',
        ),
        migrations.RenameField(
            model_name='emailonlinkclick',
            old_name='emailBody',
            new_name='email_body',
        ),
        migrations.RenameField(
            model_name='followupemail',
            old_name='emailBody',
            new_name='email_body',
        ),
    ]
