# Generated by Django 3.1.4 on 2021-02-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20210211_1708'),
        ('campaign', '0003_remove_campaignleadcatcher_is_delete'),
    ]

    operations = [
    ]
