# Generated by Django 3.1.4 on 2021-01-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_update_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='full_name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
