# Generated by Django 3.1.4 on 2021-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20210203_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrecipient',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
