# Generated by Django 3.1.4 on 2021-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20210121_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drip_email',
            old_name='days',
            new_name='waitDays',
        ),
        migrations.RenameField(
            model_name='follow_up_email',
            old_name='days',
            new_name='waitDays',
        ),
        migrations.RenameField(
            model_name='on_link_click',
            old_name='days',
            new_name='waitDays',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='emailBody',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
