# Generated by Django 3.1.4 on 2021-03-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20210319_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrecipients',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
