# Generated by Django 3.1.4 on 2021-01-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20210122_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_email',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
