# Generated by Django 3.1.4 on 2021-01-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaign_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='isActiveCampaign',
            field=models.BooleanField(default=False),
        ),
    ]
