# Generated by Django 3.1.4 on 2021-01-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaign_email_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openLead', models.CharField(max_length=200)),
                ('wonLead', models.CharField(max_length=200)),
                ('lostLead', models.CharField(max_length=200)),
                ('ignoredLead', models.CharField(max_length=200)),
            ],
        ),
    ]
