# Generated by Django 3.1.4 on 2021-01-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaignrecipient_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrecipient',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
