# Generated by Django 3.1.4 on 2021-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20210121_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='emailBody',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='subject',
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='emailBody',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='subject',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
