# Generated by Django 3.1.4 on 2021-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20210319_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='csv_fields',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_subject',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_drips',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='replacement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
