# Generated by Django 3.1.4 on 2021-01-28 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20210128_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrecipient',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
