# Generated by Django 3.1.4 on 2021-01-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_campaign_email_leadtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign_email',
            name='leadType',
        ),
    ]
