# Generated by Django 3.1.4 on 2021-03-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20210320_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dripemailmodel',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dripemailmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='dripemailmodel',
            name='waitDays',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='followupemail',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupemail',
            name='subject',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='followupemail',
            name='waitDays',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
