# Generated by Django 3.1.4 on 2021-01-28 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20210128_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrecipient',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='update_date_time',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
