# Generated by Django 3.1.4 on 2021-03-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20210324_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=50)),
                ('recipient_email', models.CharField(max_length=50)),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('email_type', models.PositiveSmallIntegerField(default=0, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0, null=True)),
                ('wait_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('sent_time', models.TimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
