# Generated by Django 3.1.4 on 2021-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_campaign_email_leadtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign_email',
            name='leadType',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('openLead', 'openLead'), ('wonLead', 'wonLead'), ('lostLead', 'lostLead'), ('ignoredLead', 'ignoredLead')], default='none', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='LeadType',
        ),
    ]
