# Generated by Django 3.1.4 on 2021-03-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0006_sendingcalendar'),
        ('campaign', '0010_sendingobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingobject',
            name='from_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailaccounts.emailaccount'),
        ),
    ]
