# Generated by Django 3.1.4 on 2021-01-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_auto_20210122_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign_email',
            old_name='leadType',
            new_name='leadStatus',
        ),
    ]
