# Generated by Django 3.1.4 on 2021-01-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20210122_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_email',
            name='company_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='role',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
