# Generated by Django 3.1.4 on 2021-03-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20210325_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dripemailmodel',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drips', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='followupemail',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='campaign.campaign'),
        ),
    ]
