# Generated by Django 3.1.4 on 2021-01-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20210125_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='leadCatcherRecipient',
            field=models.CharField(blank=True, choices=[(0, 'Replies'), (1, 'Open'), (2, 'Clicks any link'), (3, 'Clicks specific link')], default=0, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='of_times',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='specific_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
