# Generated by Django 3.1.4 on 2021-03-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_auto_20210327_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingobject',
            name='email_order',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
