# Generated by Django 3.1.4 on 2021-01-25 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0013_auto_20210125_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='leadCatcherRecipient',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='of_times',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='specific_link',
        ),
        migrations.CreateModel(
            name='CampaignLeadCatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadCatcherRecipient', models.CharField(blank=True, choices=[('replies', 'Replies'), ('open', 'Open'), ('click_any_link', 'Clicks any link'), ('clicks_specific_link', 'Clicks specific link')], default=0, max_length=32, null=True)),
                ('specific_link', models.URLField(blank=True, max_length=500, null=True)),
                ('of_times', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
