# Generated by Django 3.1.4 on 2021-03-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_emailinbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailinbox',
            name='email_subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='from_email',
            field=models.TextField(),
        ),
    ]
