# Generated by Django 3.1.4 on 2021-01-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_auto_20210125_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignleadcatcher',
            name='leadCatcherRecipient',
            field=models.CharField(choices=[('replies', 'Replies'), ('open', 'Open'), ('click_any_link', 'Clicks any link'), ('clicks_specific_link', 'Clicks specific link')], default=0, max_length=32),
        ),
    ]
