# Generated by Django 3.1.4 on 2021-01-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_auto_20210125_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='scheduleDateTime',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='full_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduleDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduleTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='unsubscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='update_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='reciepent_status',
            field=models.BooleanField(default=False),
        ),
    ]
