# Generated by Django 3.1.4 on 2021-03-31 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0012_auto_20210326_0916'),
        ('campaign', '0015_auto_20210330_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.PositiveSmallIntegerField(default=0, null=True)),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('wait_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('email_order', models.PositiveSmallIntegerField(default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='has_drips',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='has_follow_up',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='schedule_send',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='schedule_time',
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('replacement', models.TextField(blank=True, null=True)),
                ('sent', models.PositiveSmallIntegerField(default=0, null=True)),
                ('leads', models.PositiveSmallIntegerField(default=0, null=True)),
                ('replies', models.PositiveSmallIntegerField(default=0, null=True)),
                ('opens', models.PositiveSmallIntegerField(default=0, null=True)),
                ('bounces', models.PositiveSmallIntegerField(default=0, null=True)),
                ('clicked', models.PositiveSmallIntegerField(default=0, null=True)),
                ('lead_status', models.CharField(choices=[('none', 'None'), ('replied', 'Replied'), ('won', 'Won'), ('lost', 'Lost'), ('ignored', 'Not Interested')], default='none', max_length=32, null=True)),
                ('recipient_status', models.BooleanField(default=False)),
                ('is_unsubscribe', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('sent_time', models.TimeField(blank=True, null=True)),
                ('opened', models.PositiveIntegerField(default=0)),
                ('opened_datetime', models.DateTimeField(null=True)),
                ('clicked', models.PositiveIntegerField(default=0)),
                ('clicked_datetime', models.DateTimeField(null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaign')),
                ('email_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.emails')),
                ('from_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailaccounts.emailaccount')),
                ('recipient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.recipient')),
            ],
        ),
        migrations.AddField(
            model_name='emails',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
    ]
