# Generated by Django 3.1.4 on 2021-03-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_auto_20210331_0859'),
        ('campaign', '0012_auto_20210325_1045'),
    ]

    operations = [
    ]
