# Generated by Django 3.1.4 on 2021-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_auto_20210128_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='unsubscribe',
        ),
        migrations.AddField(
            model_name='campaign_email',
            name='unsubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
