# Generated by Django 3.1.4 on 2021-03-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0012_auto_20210326_0916'),
        ('campaign', '0017_merge_20210331_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('sent_time', models.TimeField(blank=True, null=True)),
                ('opened', models.PositiveIntegerField(default=0)),
                ('opened_datetime', models.DateTimeField(null=True)),
                ('clicked', models.PositiveIntegerField(default=0)),
                ('clicked_datetime', models.DateTimeField(null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaign')),
                ('email_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.emails')),
                ('from_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailaccounts.emailaccount')),
                ('recipient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.recipient')),
            ],
        ),
    ]
