# Generated by Django 3.1.4 on 2021-04-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_auto_20210401_0442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
