# Generated by Django 3.1.4 on 2021-04-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_delete_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='bounces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='clicked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='leads',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='opens',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='replies',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
