# Generated by Django 3.1.4 on 2021-04-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0012_auto_20210326_0916'),
        ('campaign', '0021_auto_20210402_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='outbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.emailoutbox'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='from_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailaccounts.emailaccount'),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='recipient_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.recipient'),
        ),
    ]
