# Generated by Django 3.1.4 on 2021-04-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_auto_20210402_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLeadSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=8)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.AlterField(
            model_name='emails',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='campaign.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignLeadSettingsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('replies', 'Replies'), ('open', 'Open'), ('click_any_link', 'Clicks any link'), ('clicks_specific_link', 'Clicks specific link')], default='replies', max_length=32)),
                ('threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('extra1', models.URLField(blank=True, max_length=500, null=True)),
                ('lead_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaignleadsettings')),
            ],
        ),
    ]
