# Generated by Django 3.1.4 on 2021-04-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_auto_20210402_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=8)),
                ('replies', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('open', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('click_any_link', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('clicks_specific_link', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='CampaignLeadSettings',
        ),
    ]
