# Generated by Django 3.1.4 on 2021-04-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0025_auto_20210402_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='lead_status',
            field=models.CharField(choices=[('none', 'None'), ('open', 'Open'), ('replied', 'Replied'), ('won', 'Won'), ('lost', 'Lost'), ('ignored', 'Not Interested')], default='none', max_length=32, null=True),
        ),
    ]
