# Generated by Django 3.1.4 on 2021-04-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0026_auto_20210403_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutbox',
            name='bounced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='replied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='reply_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='SendingObject',
        ),
    ]
