# Generated by Django 3.1.4 on 2021-04-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0027_auto_20210407_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='label_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaignlabel'),
        ),
    ]
