# Generated by Django 3.1.4 on 2021-04-08 01:13

import apps.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0028_auto_20210408_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='csvfile_op1',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='email_body',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='email_subject',
        ),
        migrations.AddField(
            model_name='campaign',
            name='csvfile',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.utils.RandomFileName('csv_uploads')),
        ),
        migrations.AddField(
            model_name='campaign',
            name='csvfile_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
