# Generated by Django 3.1.4 on 2021-04-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0029_auto_20210408_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='recipient_status',
            field=models.BooleanField(default=True),
        ),
    ]
