# Generated by Django 3.1.4 on 2021-04-09 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0014_warmingmailtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0030_auto_20210409_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutbox',
            name='is_campaign',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='lead_status',
            field=models.CharField(choices=[('none', 'None'), ('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('ignored', 'Not Interested')], default='none', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='from_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailaccounts.emailaccount'),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='outbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.emailoutbox'),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='recipient_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.recipient'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.emails'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='from_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailaccounts.emailaccount'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.recipient'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='lead_status',
            field=models.CharField(choices=[('none', 'None'), ('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('ignored', 'Not Interested')], default='none', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='LeadsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_action', models.CharField(choices=[('none', 'None'), ('open', 'Open'), ('replied', 'Replied'), ('received', 'Received'), ('won', 'Won'), ('lost', 'Lost'), ('clicked', 'Clicked'), ('reopen', 'Re Opened'), ('ignored', 'Not Interested')], default='none', max_length=32, null=True)),
                ('created_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.emailinbox')),
                ('outbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.emailoutbox')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.recipient')),
            ],
        ),
    ]
