# Generated by Django 3.1.4 on 2021-04-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0031_auto_20210410_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadslog',
            name='lead_action',
            field=models.CharField(choices=[('none', 'None'), ('opened', 'Recipient: Opened Email'), ('clicked', 'Recipient: Clicked Link'), ('replied', 'Recipient: Replied'), ('sent', 'Initial mail sent'), ('me_replied', 'Me: Replied'), ('open', 'Status: Opened'), ('won', 'Status: Won'), ('lost', 'Status: Lost'), ('ignored', 'Status: Not Interested')], default='none', max_length=32, null=True),
        ),
    ]
