# Generated by Django 3.1.4 on 2021-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210417_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bcc_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
