# Generated by Django 3.1.4 on 2021-02-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(blank=True, choices=[('SMTP', 'Smtp'), ('GOOGLE', 'Google'), ('MICROSOFT', 'Microsoft')], default='Smtp', max_length=100, null=True),
        ),
    ]
