# Generated by Django 3.1.4 on 2021-02-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpmail',
            name='provider',
            field=models.CharField(blank=True, choices=[('smtp', 'Smtp'), ('google', 'Google'), ('microsoft', 'Microsoft')], default='Smtp', max_length=100, null=True),
        ),
    ]
