# Generated by Django 3.1.4 on 2021-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0002_auto_20210306_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='use_imap_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='use_smtp_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
