# Generated by Django 3.1.4 on 2021-03-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0004_emailaccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='email_provider',
            field=models.CharField(blank=True, choices=[('SMTP', 'SMTP'), ('Google', 'Google'), ('Microsoft', 'Microsoft')], default='SMTP', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
