# Generated by Django 3.1.4 on 2021-03-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0009_auto_20210325_0802'),
        ('mailaccounts', '0008_emailaccount_warming_enabled'),
    ]

    operations = [
    ]
