# Generated by Django 3.1.4 on 2021-03-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0011_auto_20210326_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warmingstatus',
            name='status_updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
