# Generated by Django 3.1.4 on 2021-04-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0012_auto_20210326_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarstatus',
            name='sending_calendar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailaccounts.sendingcalendar'),
        ),
        migrations.AlterField(
            model_name='sendingcalendar',
            name='mail_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailaccounts.emailaccount'),
        ),
    ]
