# Generated by Django 3.1.4 on 2021-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailaccounts', '0013_auto_20210408_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmingMailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
